### ISSUE TITLE
Fatal error: Delay < 0 during reconnect

### ISSUE THREAD

**Issue by oliverhausler** [nkzawa/socket.io-client.java#110] opened 2015-03-02 14:37 UTC
I had added this to an existing error yesterday, but it happened a second time and may not be related so I'll make it a new one. Please look at #90 where I posted info that socket.io crashes, probably caused by a negative timeout value calculated by backoff.

**Comment by nkzawa** [comment] 2015-03-07 13:34
Duplicate of #107.

**Closed by nkzawa** 2015-03-07 13:34 UTC
