### ISSUE TITLE
Reconnect

### ISSUE THREAD

**Issue by ZhangPeibin** [nkzawa/socket.io-client.java#179] opened 2015-07-02 10:53 UTC
How can I reconnect when the socket disconnect?

**Comment by shuoli84** [comment] 2015-07-03 03:45
You can listen event "Disconnect" and call socket.connect() in the handler. 

Note: If the disconnect caused by network error etc, the library will reconnect.

**Comment by nkzawa** [comment] 2015-07-03 03:59
Yeah, right. Thx, @shuoli84 .

**Comment by shuoli84** [comment] 2015-07-06 11:31
@ZhangPeibin close this?

**Comment by ZhangPeibin** [comment] 2015-07-17 03:18
@shuoli84 Thanks !

**Closed** 2015-07-17 03:18 UTC
